ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;
using DataCore.Entity;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class AdminController : Controller
    {
        private readonly ServicesFacade _facade;

        public AdminController()
        {
            _facade = new ServicesFacade();
        }

        #region main
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            var model = new ComboHomeViewModel();
            model.Dishes = _facade.GetDishes();
            model.Kitchens = _facade.GetKitchens();
            model.Recipes = _facade.GetRecipes();
            return View(model);
        }

        //
        // GET: /Admin/Details/5
        public ActionResult Details(int id)
        {           
            return View();
        }

        //
        // GET: /Admin/Create
        public ActionResult Create()
        {          
            return View();
        }

        //
        // POST: /Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DishViewModel model)
        {
           try
            {
                // TODO: Add update logic here
             
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/Delete/5
        public ActionResult Delete(int id)
        {          
            return View();
        }

        //
        // POST: /Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region dish
        public ActionResult ListDishes()
        {
            var model = new ComboHomeViewModel();
            model.Dishes = _facade.GetDishes();
            return View(model);
        }

        public ActionResult CreateDish()
        {
            var model = new DishViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateDish(DishViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.AddDish(new Dish(model.Name, model.Cost, model.Description, model.Rating, model.NameKitchen, model.NamePicture));
                return RedirectToAction("ListDishes");
            }
            return View(model);
        }

        public ActionResult DeleteDish(int id)
        {
            _facade.DeleteDish(id);
            return RedirectToAction("ListDishes");
        }

        public ActionResult EditDish(int id)
        {
            var model = new DishViewModel();

            var dish = _facade.GetDish(id);

            model.Name = dish.Name;
            model.Description = dish.Description;
            model.Cost = dish.Cost;
            model.Rating = dish.Rating;
            model.NameKitchen = dish.NameKitchen;
            model.NamePicture = dish.NamePicture;

            return View(model);
        }

        [HttpPost]
        public ActionResult EditDish(int id, DishViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.EditDish(id, new Dish(model.Name, model.Cost, model.Description, model.Rating, model.NameKitchen, model.NamePicture));                         
                // todo: для обновления объекта по данным из модели
               return RedirectToAction("ListDishes");
            }
            return View(model);            
        }
        #endregion

        #region kitchen
        public ActionResult ListKitchenes()
        {
            var model = new ComboHomeViewModel();
            model.Kitchens = _facade.GetKitchens();
            return View(model);
        }

        public ActionResult CreateKitchen()
        {
            var model = new KitchenViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateKitchen(KitchenViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.AddKitchen(new Kitchen(model.Name, model.Description, model.NamePicture));
                return RedirectToAction("ListKitchenes");
            }            
                return View();
        }

        public ActionResult DeleteKitchen(int id)
        {
            _facade.DeleteKitchen(id);
            return RedirectToAction("ListKitchenes");
        }

        public ActionResult EditKitchen(int id)
        {
            var model = new KitchenViewModel();

            var kitchen = _facade.GetKitchen(id);

            model.Name = kitchen.Name;
            model.Description = kitchen.Description;
            model.NamePicture = kitchen.NamePicture;

            return View(model);
        }

        [HttpPost]
        public ActionResult EditKitchen(int id, KitchenViewModel model)
        {          
                if (ModelState.IsValid)
                {
                    _facade.EditKitchen(id, new Kitchen(model.Name, model.Description, model.NamePicture));
                }
                return RedirectToAction("ListKitchenes");     
        }
#endregion

        #region recipe
        public ActionResult ListRecipes()
        {
            var model = new ComboHomeViewModel();
            model.Recipes = _facade.GetRecipes();
            return View(model);
        }

        public ActionResult CreateRecipe()
        {
            var model = new RecipeViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateRecipe(RecipeViewModel model)
        {
            if (ModelState.IsValid)
            {
                _facade.AddRecipe(new Recipe(model.Name, model.TimeOfcooking,new[] {"gmmm"}, model.NameDish,
                    model.NamePicture, new[] {"mghg"}));
                return RedirectToAction("ListRecipes");
            }
            return View(model);
        }
        public ActionResult DeleteRecipe(int id)
        {
            _facade.DeleteRecipe(id);
            return RedirectToAction("ListRecipes");
        }
        public ActionResult EditRecipe(int id)
        {
            var model = new RecipeViewModel();

            var recipe = _facade.GetRecipe(id);

            model.Name = recipe.Name;
            model.TimeOfcooking = recipe.TimeOfcooking;
            model.NameDish = recipe.NameDish;
            model.NamePicture = recipe.NamePicture;

            return View(model);
        }

        [HttpPost]
        public ActionResult EditRecipe(int id, RecipeViewModel model)
        {
            if (ModelState.IsValid)
            {               
                string[] st=_facade.GetRecipe(id).Steps;
                string[] imgs = _facade.GetRecipe(id).RecipeInImages;
                _facade.EditRecipe(id, new Recipe( model.Name, model.TimeOfcooking, st, model.NameDish,
                    model.NamePicture, imgs));

                return RedirectToAction("ListRecipes");
            }
            return View(model);
        }
        #endregion
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/KitchenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;
using DataCore.Entity;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class KitchenController : Controller
    {
        private readonly ServicesFacade _facade;

        public KitchenController()
        {
            _facade = new ServicesFacade();
        }

        public ActionResult Index()
        {
            return View(;
        }

        public ActionResult Details(int id)
        {
            var model = new KitchenInfoViewModel();

            model.Kitchen = _facade.GetKitchen(id);
            model.Dishes = _facade.GetDishesForKitchen(model.Kitchen.Id);
            
            return View(model);
        }

        public ActionResult SortedDishes(string sort, int id)
        {
            var model = new KitchenInfoViewModel();
            model.Kitchen = _facade.GetKitchen(id);
            switch (sort)
            {
                case "Name": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfName()); } break;
                case "Cost": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfCost()); } break;
                case "Rating": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfRating()).Reverse(); } break;
                default:
                    {
                        model.Dishes = _facade.GetDishes();
                    } break;
            }
            return View(model);
        }
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class RecipeController : Controller
    {
        private readonly ServicesFacade _facade;

        public RecipeController()
        {
            _facade = new ServicesFacade();
        }
        //
        // GET: /Recipe/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Recipe/Details/5
        public ActionResult Details(int id)
        {
            var model = new RecipeInfoModel();

            model.Recipe = _facade.GetRecipe(id);

            model.Ingredients = _facade.GetIngredientsForDish(model.Recipe.Id);

            return View(model);
        }

        //
        // GET: /Recipe/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Recipe/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Recipe/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Recipe/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Recipe/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Recipe/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/CreateDish.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.DishViewModel

@{
    ViewBag.Title = "CreateDish";
}

<h2>CreateDish</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost)
                @Html.ValidationMessageFor(model => model.Cost)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating)
                @Html.ValidationMessageFor(model => model.Rating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameKitchen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameKitchen)
                @Html.ValidationMessageFor(model => model.NameKitchen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListDishes")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/CreateKitchen.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.KitchenViewModel

@{
    ViewBag.Title = "CreateKitchen";
}

<h2>CreateKitchen</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListKitchenes")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/CreateRecipe.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.RecipeViewModel

@{
    ViewBag.Title = "CreateRecipe";
}

<h2>CreateRecipe</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RecipeViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfcooking, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfcooking)
                @Html.ValidationMessageFor(model => model.TimeOfcooking)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameDish, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameDish)
                @Html.ValidationMessageFor(model => model.NameDish)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListRecipes")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/EditDish.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.DishViewModel

@{
    ViewBag.Title = "EditDish";
}

<h2>EditDish</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost)
                @Html.ValidationMessageFor(model => model.Cost)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating)
                @Html.ValidationMessageFor(model => model.Rating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameKitchen, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameKitchen)
                @Html.ValidationMessageFor(model => model.NameKitchen)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListDishes")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/EditKitchen.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.KitchenViewModel

@{
    ViewBag.Title = "EditKitchen";
}

<h2>EditKitchen</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListKitchens")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/EditRecipe.cshtml
@model ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.RecipeViewModel

@{
    ViewBag.Title = "EditRecipe";
}

<h2>EditRecipe</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfcooking, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfcooking)
                @Html.ValidationMessageFor(model => model.TimeOfcooking)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameDish, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameDish)
                @Html.ValidationMessageFor(model => model.NameDish)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamePicture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamePicture)
                @Html.ValidationMessageFor(model => model.NamePicture)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListRecipes")
</div>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/Index.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel

@{
    ViewBag.Title = "Index";
}
<ul class="nav nav-tabs">
    <li class="active"><a href="@Url.Action("Index", "Admin")">Нome</a></li>
    <li><a href="@Url.Action("ListKitchenes", "Admin")">Kitchens</a></li>
    <li><a href="@Url.Action("ListDishes", "Admin")">Dishes</a></li>
    <li><a href="@Url.Action("ListRecipes", "Admin")">Recipes</a></li>
</ul>
@*@Html.ActionLink("Dishes", "ListDishes", "Admin")
@Html.ActionLink("Kitchens", "ListKitchenes", "Admin")
@Html.ActionLink("Recipes", "ListRecipes", "Admin")*@

Hello, I home page.
 
If you want edit something Click on thу appropriate tab.

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/ListDishes.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel

    @{
        ViewBag.Title = "ListDishes";
    }
<ul class="nav nav-tabs">
    <li ><a href="@Url.Action("Index", "Admin")">Нome</a></li>
    <li><a href="@Url.Action("ListKitchenes", "Admin")">Kitchens</a></li>
    <li class="active"><a href="@Url.Action("ListDishes", "Admin")">Dishes</a></li>
    <li><a href="@Url.Action("ListRecipes", "Admin")">Recipes</a></li>
</ul>
    <h2>ListDishes</h2>

    <p>
        @Html.ActionLink("Create New", "CreateDish")
    </p>
    <table class="table">
        <tr>
            <th></th>
        </tr>

        @foreach (var item in Model.Dishes)
        {
            <tr>
                <td>
                    @item.Name
                    @Html.ActionLink("Edit", "EditDish", new { id = item.Id }) |
                    @*@Html.ActionLink("Details", "Details", "Dishes", new { id=item.Id })*@
                    <a href="@Url.Action("Details", "Dishes", new { id = item.Id })">Details</a>|
                    @Html.ActionLink("Delete", "DeleteDish", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/ListKitchenes.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel

@{
    ViewBag.Title = "ListKitchen";
}
<ul class="nav nav-tabs">
    <li ><a href="@Url.Action("Index", "Admin")">Нome</a></li>
    <li class="active"><a href="@Url.Action("ListKitchenes", "Admin")">Kitchens</a></li>
    <li><a href="@Url.Action("ListDishes", "Admin")">Dishes</a></li>
    <li><a href="@Url.Action("ListRecipes", "Admin")">Recipes</a></li>
</ul>
<h2>ListKitchen</h2>

<p>
    @Html.ActionLink("Create New", "CreateKitchen")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model.Kitchens) {
    <tr>
        <td>
            @item.Name
            @Html.ActionLink("Edit", "EditKitchen", new {  id=item.Id }) |
            @*@Html.ActionLink("Details", "Details", new {  id=item.Id }) |*@
            <a href="@Url.Action("Details", "Kitchen", new { id = item.Id })">Details</a>|
            @Html.ActionLink("Delete", "DeleteKitchen", new {  id=item.Id })
        </td>
    </tr>
}

</table>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Admin/ListRecipes.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel

@{
    ViewBag.Title = "ListRecipes";
}
<ul class="nav nav-tabs">
    <li ><a href="@Url.Action("Index", "Admin")">Нome</a></li>
    <li><a href="@Url.Action("ListKitchenes", "Admin")">Kitchens</a></li>
    <li><a href="@Url.Action("ListDishes", "Admin")">Dishes</a></li>
    <li class ="active"><a href="@Url.Action("ListRecipes", "Admin")">Recipes</a></liclass>
</ul>
<h2>ListRecipes</h2>

<p>
    @Html.ActionLink("Create New", "CreateRecipe")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model.Recipes) {
    <tr>
        <td>
            @item.Name
            @Html.ActionLink("Edit", "EditRecipe", new {  id=item.Id }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.Id }) |*@
            <a href="@Url.Action("Details", "Recipe", new { id = item.Id })">Details</a>|
            @Html.ActionLink("Delete", "DeleteRecipe", new { id=item.Id})
        </td>
    </tr>
}

</table>