ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/DishesController.cs
using System.Collections;
using System.Globalization;
using System.Linq;
using System.Web.DynamicData;
using System.Web.Mvc;
using Antlr.Runtime.Misc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;
using DataCore.Sort;
using DataCore.Sort.SortRecipes;
using SortOfName = DataCore.Sort.SortOfName;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class DishesController : Controller
    {
        private readonly ServicesFacade _facade;

        public DishesController()
        {
            _facade = new ServicesFacade();
        }

        //
        // GET: /Dishes/
        public ActionResult Index()
        {        
            return View();
        }

        //
        // GET: /Dishes/Details/5
        public ActionResult Details(int id)
        {
            var model = new DishInfoViewModel();

            model.Dish = _facade.GetDish(id);   

            model.Recipes = _facade.GetRecipesForDish(id);
            
            return View(model);
        }
        
        // GET: /Dishes/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Dishes/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                if (collection != null)
                {
                    object k=collection.Get(0);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Dishes/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Dishes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Dishes/Delete/5
        public ActionResult Delete(int id)
        {       
            return View();
        }

        //
        // POST: /Dishes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult SortedRecipes(string sort, int id)
        { 
        var model = new DishInfoViewModel();
            model.Dish = _facade.GetDish(id);
            switch (sort)
            {
                case "Name":
                {
                    model.Recipes = _facade.GetRecipesForDish(id)
                        .OrderBy(recipe => recipe, new DataCore.Sort.SortRecipes.SortOfName());
                }break;
                case "Time":
                {
                    model.Recipes = _facade.GetRecipesForDish(id).OrderBy(recipe => recipe, new SortOfTime());
                }break;
                default:
                {
                    model.Recipes = _facade.GetRecipesForDish(id);
                }break;
            }
            return View(model);

        }
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;
using DataCore.Entity;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ServicesFacade _facade;

        public HomeController()
        {
            _facade = new ServicesFacade();
        }

        public ActionResult Index()
        {
             var model = new ComboHomeViewModel();

            model.Kitchens = _facade.GetKitchens();
            model.Dishes = _facade.GetDishes();

            return View(model);
        }

        public ActionResult SearchDish(string name)
        {
            var model = new DishInfoViewModel();
            model.Dish = _facade.GetDish(name);
            return View(model);
        }    

        public ActionResult SortedDishes(string sort)
        {
            var model = new ComboHomeViewModel();
            model.Kitchens = _facade.GetKitchens();
            switch (sort)
            {
                case "Name": { model.Dishes = _facade.GetDishes().OrderBy(dish => dish, new DataCore.Sort.SortOfName()); } break;
                case "Cost": { model.Dishes = _facade.GetDishes().OrderBy(dish => dish, new DataCore.Sort.SortOfCost()); }break;
                case "Rating": { model.Dishes = _facade.GetDishes().OrderBy(dish => dish, new DataCore.Sort.SortOfRating()).Reverse(); } break;
                default:
                {
                    model.Dishes = _facade.GetDishes();
                } break;
            }
            return View(model);           
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Controllers/KitchenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Infrastructure;
using ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels;
using DataCore.Entity;

namespace ASP.NET_MVC5_with_Bootstrap_3._1._1_LESS1.Controllers
{
    public class KitchenController : Controller
    {
        private readonly ServicesFacade _facade;

        public KitchenController()
        {
            _facade = new ServicesFacade();
        }

        public ActionResult Index()
        {
            return View(;
        }

        public ActionResult Details(int id)
        {
            var model = new KitchenInfoViewModel();

            model.Kitchen = _facade.GetKitchen(id);
            model.Dishes = _facade.GetDishesForKitchen(model.Kitchen.Id);
            
            return View(model);
        }

        public ActionResult SortedDishes(string sort, int id)
        {
            var model = new KitchenInfoViewModel();
            model.Kitchen = _facade.GetKitchen(id);
            switch (sort)
            {
                case "Name": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfName()); } break;
                case "Cost": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfCost()); } break;
                case "Rating": { model.Dishes = _facade.GetDishesForKitchen(id).OrderBy(dish => dish, new DataCore.Sort.SortOfRating()).Reverse(); } break;
                default:
                    {
                        model.Dishes = _facade.GetDishes();
                    } break;
            }
            return View(model);
        }
    }
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

<p>This app is a culinary reference</p>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

<address>
    <img src="~/Content/img/no-avatar.jpg" />
   <br/> Student group IT-22
</address>

<address>
    <strong>E-mail:</strong> <a href="ann9510@mail.ru">ann9510@mail.ru</a>
</address>

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Home/Index.cshtml
@using System.ServiceModel.Configuration
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="active item"><center><img src="~/Content/img/main.jpg" /></center></div>
            @foreach (var item in Model.Kitchens)
            {
                <div class="item"><center><a href="@Url.Action("Details", "Kitchen", new { id = item.Id })"><img src="~/Content/img/Carousel/@item.NamePicture" /></a> </center></div>
            }

        </div>
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>


    <div class="row">
        <div class="col-lg-3">
            <h2 class="page-header">
                Search dish
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Enter the name of the dish..." id="search">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default" onclick="searchbuttonclick()">

                            <span class="glyphicon glyphicon-search"></span>

                        </button>

                    </span>
                </div>
            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Dishes
                <small class="pull-right">
                    Sort of
                    <select class="span2" id="my_select" onchange="sortbuttonclick()">
                        <option value=""></option>
                        <option value="Name">Name</option>
                        <option value="Cost">Cost</option>
                        <option value="Rating">Rating</option>
                    </select>
                </small>
            </h1>
        </div>
    </div>

    <script>
        function sortbuttonclick() {
            var sort = $("#my_select option:selected").val();
            $.get("/Home/SortedDishes?sort=" + sort, function (data) {
                $("#dishes").empty();
                $("#dishes").html(data);
            });
        }

        function searchbuttonclick() {
            var name = $("#search").val();
            $.get("/Home/SearchDish?name=" + name, function (data) {
                $("#dishes").empty();
                $("#dishes").html(data);
            });
        }
    </script>

    <div class="row" id="dishes">
        @foreach (var item in Model.Dishes)
        {
            <a href="@Url.Action("Details", "Dishes", new { id = item.Id })">
                <div class="col-lg-4 col-sm-6">
                    <img class="img-circle img-responsive" src="~/Content/img/dishes/@item.NamePicture">
                    <h3>
                        @item.Name
                        <small>@item.Cost br</small>
                    </h3>
                </div>
            </a>
        }
    </div>
</div>   

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Home/SearchDish.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.DishInfoViewModel

@{
    Layout = null;
}
@if (Model.Dish != null)
{
    <a href="@Url.Action("Details", "Dishes", new {id = Model.Dish.Id})">
        <div class="col-lg-4 col-sm-6">
            <img class="img-circle img-responsive" src="~/Content/img/dishes/@Model.Dish.NamePicture">
            <h3>
                @Model.Dish.Name
                <small>@Model.Dish.Cost br</small>
            </h3>
        </div>
    </a>
}

ASP.NET MVC5 with Bootstrap 3.1.1 LESS1/Views/Home/SortedDishes.cshtml
@model NET_MVC5_with_Bootstrap_3._1._1_LESS1.Models.ViewModels.ComboHomeViewModel

@{
    Layout = null;
}

@foreach (var item in Model.Dishes)
{
    <a href="@Url.Action("Details", "Dishes", new { id = item.Id })">
        <div class="col-lg-4 col-sm-6">
            <img class="img-circle img-responsive" src="~/Content/img/dishes/@item.NamePicture">
            <h3>
                @item.Name
                <small>@item.Cost br</small>
            </h3>
        </div>
    </a>
}